### ISSUE TITLE
关于pcxFirefox thunderbird

### ISSUE THREAD

**Issue by vimac** [xunxun1982/pcxfirefox#14]
我从mozilla的bugzilla的一个链接 https://bugzilla.mozilla.org/show_bug.cgi?id=653342 找到这里的，那个链接里面提到了你的thunderbird的release修复了thunderbird的撰写邮件会插入多余字符的bug，但是不清楚你最终用的是哪个补丁，在sf.net上也没有看到链接，所以来这里请教一下

（我是Mac用户，所以无法用你预编译的那个版本，打算自己打补丁编译）

**Comment by xunxun1982** [comment]
才发现thunderbird的补丁留在本地了 没有向github做push操作

现在应该有了，你可以参考
https://github.com/xunxun1982/pcxfirefox/blob/master/patches/release/thunderbird/esr/24esr/mail/bug653342.patch

**Comment by vimac** [comment]
好的，非常感谢

**Comment by asmwarrior** [comment]
[Comment 177](https://bugzilla.mozilla.org/show_bug.cgi?id=653342#c177) 那个bug zilla上面出新的patch和编译二进制版本了，大伙儿可以去测试一下。

**Comment by xunxun1982** [comment]
@asmwarrior 我现在都没时间维护了。。。 都没有电脑用。。。宁愿用有限的时间看看gcc的进展

**Comment by asmwarrior** [comment]
@xunxun1982 是啊，编译thunderbird不是一般人能干的。我上面的回复只是给大家提个醒，这个多年的bug，现在总算有牛人要修复它了。
