### ISSUE TITLE
Installation of pcxfirefox

### ISSUE THREAD

**Issue by sanon** [xunxun1982/pcxfirefox#15]
Hi,

I have downloaded the .7z file from Sourceforge and extracted it to a folder. After I open it clicking the firefox.exe file in that folder it seems as if the official version of firefox opens. I also haven't seen anything related to pcxfirefox under the Help menu.

Any suggestions?

**Comment by xunxun1982** [comment]
pcxFirefox is a firefox custom build, not a solo product, which ( full edition ) is compatible with the same official edition, so it will use official edition's profile by default.
But you can also use the internal portable mode ( change tmemutil-sample.ini to tmemutil.ini, set Portable=1 in tmemutil.ini ), I have written the details in ReadMe.

Of course, all custom builds claimed being compatible with official edition should use official edition's profile by default.
