### ISSUE TITLE
39.0 x64 crash

### ISSUE THREAD

**Issue by fhoshino** [xunxun1982/pcxfirefox#17]
Getting the following crash when using webogram.

Faulting application name: firefox.exe, version: 39.0.0.5654, time stamp: 0x55937974
Faulting module name: xul.dll, version: 39.0.0.5654, time stamp: 0x5593897b
Exception code: 0xc0000005
Fault offset: 0x000000000057c595
Faulting process id: 0x1ad4
Faulting application start time: 0x01d0b72a1db395d7
Faulting application path: C:\Firefox\firefox\firefox.exe
Faulting module path: C:\Firefox\firefox\xul.dll
Report Id: 90f8f25a-231d-11e5-bfd9-00116b671f30
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fhoshino** [comment]
x86 version has this crash too, but less often.

Faulting application name: firefox.exe, version: 39.0.0.5654, time stamp: 0x55936601
Faulting module name: xul.dll, version: 39.0.0.5654, time stamp: 0x55937113
Exception code: 0xc0000005
Fault offset: 0x00603f1c
Faulting process id: 0x24c8
Faulting application start time: 0x01d0b86c3dc471ab
Faulting application path: C:\Firefox\firefox\firefox.exe
Faulting module path: C:\Firefox\firefox\xul.dll
Report Id: 40735cfb-2468-11e5-bfd9-00116b671f30
Faulting package full name: 
Faulting package-relative application ID:

**Comment by xunxun1982** [comment]
What is webogram?

If you want to provide the crash information, you can set CreateCrashDump=1 in tmemutil.ini, after crashing, pcxfirefox.dmp will be created in %appdata% path. I need the dmp file.

**Comment by fhoshino** [comment]
Webogram is the web implementation of Telegram
https://web.telegram.org/

I'll try to get I dump when I have time.

**Comment by fhoshino** [comment]
Crash dump seems not creating correctly, it produce a 0 byte file in AppData\Roaming folder.
