### ISSUE TITLE
41.0 x64: cannot switch video quality on youtube.com

### ISSUE THREAD

**Issue by patwonder** [xunxun1982/pcxfirefox#18]
Steps to reproduce:
1. Open https://www.youtube.com/watch?v=J_cxoZLPyR0 .
2. Try switch to a different video quality than "auto".
3. Observe what happens.

Expected result:
Video plays with the new quality setting.

Actual result:
Video stops streaming. There's a console error:
InvalidAccessError: A parameter or an operation is not supported by the underlying object

Reproducible:
Always.

Notes:
The issue does not occur on official 41.0 x64 beta.

**Comment by xunxun1982** [comment]
Thanks, I will try to fix it.
btw, can you reproduce the plugin-container hang in tieba/kafan/some video sites ( x86 and x64 edition )?

**Comment by xunxun1982** [comment]
你下载这个解压覆盖到64位版本的试试
https://sourceforge.net/projects/pcxfirefox/files/Test/Firefox/Fx41x64fix/

**Comment by patwonder** [comment]
@xunxun1982 覆盖后正常。
我能知道原因么？

**Comment by patwonder** [comment]
@xunxun1982 Cannot reproduce plugin-container hang on x64 version after the fix. Not sure whether it happens before the fix.
Maybe it's a sandbox issue?
![plugin-container sandbox](https://cloud.githubusercontent.com/assets/1505712/10073596/aab6fd64-62fc-11e5-9da8-2594b0d531f1.png)

**Comment by xunxun1982** [comment]
不是沙盒原因 由于我在手机上 就简单说下思路

这种问题一看到差不多和layout或者media或者dom模块有关 既然官方版没有问题导致的原因无非是我采用的额外补丁 pgo优化 以及fastmath 前二者很容易排除(根据我本地的调试版) 那么基本就剩fastmath了 因为youtube播放器的拖拉和调整画质很容易想到mediasource模块 所以尝试将dom/media/mediasource模块取消fastmath 再差分构建 问题解决

由此可见 vc2013 x64的fastmath bug有些多 所以我打算提高64位版本的浮点精确性 不再进行fastmath优化    至于32位版本保留是否还待观察 毕竟64位编译器之前发现过多次此类问题了 以前你们没发现是因为我自己提前解决了 32位版本至今没发现此类问题

**Comment by xunxun1982** [comment]
@parwonder 
另外 贴吧那个bug你能重现吗？

**Comment by xunxun1982** [comment]
@patwonder

**Comment by patwonder** [comment]
@xunxun1982 谢谢解释~~ 贴吧那个似乎不能重现。。
