### ISSUE TITLE
No performance tool in dev toolbox?

### ISSUE THREAD

**Issue by patwonder** [xunxun1982/pcxfirefox#19]
Official 41.0b9 x64:
![official 41 0b9 x64](https://cloud.githubusercontent.com/assets/1505712/10118364/b069126c-64a8-11e5-8005-092a3d52a7fc.png)

pcx 41.0 x64:
![pcx 41 0 x64 perf tab missing](https://cloud.githubusercontent.com/assets/1505712/10118392/2a9a8cc8-64a9-11e5-9cca-028f65e538bb.png)

**Comment by xunxun1982** [comment]
I guess it's related with MOZ_ENABLE_PROFILER_SPS : https://mxr.mozilla.org/mozilla-central/search?string=MOZ_ENABLE_PROFILER_SPS&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=mozilla-central

I disabled the macro, but no body reported any bug related about it.
So I will enable it next edition, only may disable it in my future Lite edition.

**Comment by patwonder** [comment]
@xunxun1982 Does this macro affect JavaScript performance? It's OK to leave it off. I'll use the official version if I'm going do any serious profiling.

**Comment by xunxun1982** [comment]
No, I think that affect the performance very little.

My 42.0 is released, so the issue is fixed.

**Comment by patwonder** [comment]
Great!
