### ISSUE TITLE
don't start with Portable=1 and TmpDataPath=r:\cache\

### ISSUE THREAD

**Issue by f242** [xunxun1982/pcxfirefox#20]
pcxFirefox don't start with Portable=1 and TmpDataPath=r:\cache\ (R - is my ramdisk with cache folder)
it appears in task manager, but main window not displayed
if i set blank TmpDataPath= all works fine

**Comment by xunxun1982** [comment]
Works fine in my XP, Win7 SP1 x64, win8.1 x64, Win10 x64.
Maybe you should create a new profile first.

**Comment by f242** [comment]
i recorded video
[2016-02-13_19-16-43.zip](https://github.com/xunxun1982/pcxfirefox/files/129244/2016-02-13_19-16-43.zip)

**Comment by xunxun1982** [comment]
I can't open the video, my player said it was broken.

**Comment by f242** [comment]
@xunxun1982 
it was h265 mp4
i converted it to h264 mkv https://www.mediafire.com/?50bs9a7nawez2r1
