### ISSUE TITLE
Processpriority setting doesn't affect plugin-container.exe priority

### ISSUE THREAD

**Issue by toad01** [xunxun1982/pcxfirefox#22]
Hi,

With version 49.0.1 setting pcxfirefox.processpriority.firefox.level to 0 (i.e. Normal) only affects firefox.exe. Plugin-container.exe remains at Above Normal.

Adrian

**Comment by xunxun1982** [comment]
This is a technical reason: I can't solve it unless pass the environment value ( not about:config ).
But in future, firefox will enable firefox.exe to handle the e10s content, not plugin-container.exe, then the problem will disappear.
At present, I can pass an environment value to tmemutil.ini / OS, maybe finished it in 50.x+

**Comment by toad01** [comment]
Ok, thank you. I thought in a previous version I had been able to reset the priority plugin-container.exe. Must have been imagining it!

Anyway, I would like to say that I've been using pcxfirefox for a couple of years now, and it has been the most reliable browser I have used (I've tried most of the Firefox variants), I don't think it has ever crashed. Keep up the good work!

Adrian

**Comment by xunxun1982** [comment]
In 50.0, pcxfirefox.processpriority.firefox.level should control plugin-container.exe

https://sourceforge.net/projects/pcxfirefox/files/Release/Firefox/50.x/50.0/

**Comment by xunxun1982** [comment]
I found that the feature will cause some problems, I will investigate it later, and will delay 50.0 to 50.0.1
