### ISSUE TITLE
NPAPI plugins support in version 49.0.2

### ISSUE THREAD

**Issue by thumbapps** [xunxun1982/pcxfirefox#24]
First of all, thanks for a better Firefox fork build, Xunxun :)

We notice that in the latest release 49.0.2, support for NPAPI plugins becomes similar to the official release, i.e.:
- 32-bit: can detect Flash Player but won't run it. It can detect and run Silverlight and Java.
- 64-bit: can't detect and run Java. It can detect and run Flash Player and Silverlight.
  This characteristic is similar the the official version.

We like better your 49.0.1 release, cause both the 32 and 64 bit can detect and run all NPAPI plugins.

We hope you can fix it in your next release. We don't release our portable version 49.0.2 because of this. We release it on our http://thumbapps.org: http://www.thumbapps.org/2016/10/pcxFirefox-portable-32-64-bit-optimized-faster-Mozilla-Firefox-variant.html.

Thanks for the good work!

Regards,
Ronny
thumbapps.org

**Comment by xunxun1982** [comment]
It's strange, and x86/x64 editions both work well on my Win10 x64.
Maybe it's an official source code bug in plugin async rendering ( since 49.0.2 ).

Try to set dom.ipc.plugins.asyncdrawing.enabled to false and restart firefox to check it again.

**Comment by thumbapps** [comment]
Sorry for the late response. I got major system breakdown for 3 days... :(

I've tried it but still not working. Why was it all working in 49.0.1? It's the best one to date.

**Comment by thumbapps** [comment]
Sorry for the late reply. We got major system breakdown for 3 days... Lots of updates backlog...even now :(

But yes, your suggestion work.

Xie xie!
