### ISSUE TITLE
pcxfirefox49.02 flash video freez 

### ISSUE THREAD

**Issue by 117649** [xunxun1982/pcxfirefox#25]
jumped from 48.02 to 49.02 and this problem occurs then drop down to 49.01 it seems fine by now.

the problem which can be describe as while playing a video via flash player the entire area of the flash player display refuse to refresh. It freezes at the last frame since the last time the display area of the entire page is changed(i.e: scroll up or down in the page) however the sound will play normally. If the page is the current tab after restored a session this problem won't occur until switch to another tab. The freeze is to the entire flash display area and all elements within it won't respond not only the video it plays.

I'm running X64 pcxfirefox on a win10 PC with flash 23.00.7 installed and all hardware accelerate option are switched to off.

**Comment by xunxun1982** [comment]
Closed same with #24
