### ISSUE TITLE
pcxFirefox questions

### ISSUE THREAD

**Issue by mugwampbro** [xunxun1982/pcxfirefox#26]
windows 7 Home premium x64 

I have been using Firefox 50.1.0 and yesterday I downloaded 
 pcxFirefox-50.1.0-enUS-vc2015-x64-sse2-betterpgo-161213

Questions:

1)How to correctly install on my computer?
****I opened the .zip file on my desktop but their is no install button. I  pressed the Firefox.exe (included in the package) and it opened Firefox...but in the "about Firefox" tab, it doesn't say anything about pcxFirefox. There is also no pcxFirefox in C:programs.....just the regular version. 

I am new to custom Firefox builds, so sorry if these questions seem stupid. I have searched the web for hours to find more info about pcxFirefoxm but I can NOT find answers to the many questions I have such as...

2) once pcxFirefox is correctly installed, can I then delete the regular version of Firefox?

**Comment by sleek22** [comment]
I unzipped pcxFirefox and moved the resulting folder into C:\Program Files and made a shortcut to the executable. I also made it so Windows would use that as my default browser.

I uninstalled the regular version of Firefox.

To be on the safe side, before uninstalling the regular version of Firefox, make a copy of your profile folder and store it somewhere. If by chance it gets deleted or changed, you'll have that backup copy.

Hope that helps.
