### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by InstallGentoo11** [xunxun1982/pcxfirefox#29]
Why close the thread so fast? And why did you reply as if pcxfirefox is not suppose to be used with addons and scripts at all? Surely it is not like that?
It works just fine in one version, but not another? I doubt that the problem is within some simple addon. I am not using anything special to begin with. I doubt something like ublock origin makes a big difference. And the thing that ultimately changed was the firefox version, not the addons. So I really don't understand the hostility.

**Comment by xunxun1982** [comment]
I won't handle any problems related with the same official source code or some addons, except if you can make sure your problems only exist my edition and not in official edition.
Please don't ask any questions with obvious answers.
